name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: communication_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_pgsql
          coverage: xdebug
          tools: composer:v2
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Set up database schema
        run: |
          # Create the database tables needed for tests
          PGPASSWORD=postgres psql -h localhost -U postgres -d communication_test -c "$(cat migrations/V1__create_communication_definitions.sql)"
          PGPASSWORD=postgres psql -h localhost -U postgres -d communication_test -c "$(cat migrations/V2__create_templates.sql)"
      
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: communication_test
          POSTGRES_PORT: 5432
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
